### ISSUE TITLE
Rename deploy and deployAll tasks to highlight its purpose

### ISSUE THREAD

**Issue by toplac** [qaware/gradle-cloud-deployer#44]
When using the plugin as a part of a continuous delivery pipeline, the name of the tasks can be confusing. 
For example the task deployAll could be interpretet as deploying a single unit to a Maven Repository, a docker registry and a runtime enivroment all at once. 

Suggestions for new names:
    
    ==== deploy
    deployToCloud
    cloudDeployment

    ==== deployAll
    deployAllToCloud
    batchCloudDeployment

**Comment by lreimer** [comment]
I have to agree on this one. However, the common Gradle convention is to begin the tasks with the plugin name or purpose. e.g. `cloudDeployAll`

Also, currently you have to pass a `--environmentId` if working with only one. Again, the usual Gradle convention is to have dynamic tasks names.

``` groovy
deployer {
    marathon {
        id = "marathon-zwitscher"
    }
}
```

You now should have a `cloudDeployMarathonZwitscher` and `cloudDeleteMarathonZwitscher` task. The `*All` tasks are simply a shortcut for all if the kind.

**Comment by sjahreis** [comment]
@toplac, @lreimer: will rename the tasks as @lreimer suggested and will add the possibility to have dynamic task names.

**Comment by toplac** [comment]
@sjahreis Any update?
